-- The Good Press initial database schema.
-- User-owned tables use Row Level Security so browser clients only access their own rows.

create extension if not exists pgcrypto with schema extensions;

create type public.article_status as enum ('draft', 'published', 'archived');
create type public.swipe_direction as enum ('left', 'right');

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text check (char_length(display_name) between 1 and 80),
  avatar_url text,
  theme text not null default 'system' check (theme in ('light', 'dark', 'system')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.articles (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(title) between 1 and 300),
  ai_summary text not null check (char_length(ai_summary) between 1 and 2000),
  source_name text not null check (char_length(source_name) between 1 and 120),
  source_url text not null,
  image_url text,
  category text not null check (char_length(category) between 1 and 80),
  published_at timestamptz not null,
  status public.article_status not null default 'draft',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint articles_source_url_unique unique (source_url)
);

create table public.swipes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  article_id uuid not null references public.articles (id) on delete cascade,
  direction public.swipe_direction not null,
  created_at timestamptz not null default now(),
  constraint swipes_user_article_unique unique (user_id, article_id)
);

create table public.user_agendas (
  user_id uuid primary key references auth.users (id) on delete cascade,
  preferred_categories text[] not null default '{}',
  blocked_categories text[] not null default '{}',
  preference_scores jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create index articles_feed_idx on public.articles (published_at desc) where status = 'published';
create index articles_category_idx on public.articles (category);
create index swipes_user_created_idx on public.swipes (user_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();
create trigger articles_set_updated_at before update on public.articles
for each row execute function public.set_updated_at();
create trigger user_agendas_set_updated_at before update on public.user_agendas
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(nullif(new.raw_user_meta_data ->> 'display_name', ''), split_part(new.email, '@', 1)));
  insert into public.user_agendas (user_id) values (new.id);
  return new;
end;
$$;

create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_user();

insert into public.profiles (id, display_name)
select id, coalesce(nullif(raw_user_meta_data ->> 'display_name', ''), split_part(email, '@', 1))
from auth.users on conflict (id) do nothing;
insert into public.user_agendas (user_id)
select id from auth.users on conflict (user_id) do nothing;

alter table public.profiles enable row level security;
alter table public.articles enable row level security;
alter table public.swipes enable row level security;
alter table public.user_agendas enable row level security;

create policy "Published articles are publicly readable" on public.articles
for select to anon, authenticated using (status = 'published');
create policy "Users can read their own profile" on public.profiles
for select to authenticated using ((select auth.uid()) = id);
create policy "Users can update their own profile" on public.profiles
for update to authenticated using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);
create policy "Users can read their own swipes" on public.swipes
for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users can create their own swipes" on public.swipes
for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Users can change their own swipes" on public.swipes
for update to authenticated using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
create policy "Users can delete their own swipes" on public.swipes
for delete to authenticated using ((select auth.uid()) = user_id);
create policy "Users can read their own agenda" on public.user_agendas
for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users can update their own agenda" on public.user_agendas
for update to authenticated using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

grant usage on schema public to anon, authenticated;
grant select on public.articles to anon, authenticated;
grant select, update on public.profiles to authenticated;
grant select, insert, update, delete on public.swipes to authenticated;
grant select, update on public.user_agendas to authenticated;
grant usage, select on sequence public.swipes_id_seq to authenticated;

-- n8n writes articles with its server-side Supabase credential.
