-- The Good Press initial database schema.
-- All user-owned tables use Row Level Security so browser clients can only
-- access rows belonging to the signed-in user.

create extension if not exists pgcrypto with schema extensions;

create type public.article_status as enum ('draft', 'published', 'archived');
create type public.swipe_direction as enum ('left', 'right');

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text check (char_length(display_name) between 1 and 80),
  avatar_url text,
  theme text not null default 'system' check (theme in ('light', 'dark', 'system')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- The project may already have the starter articles table created by n8n.
-- Keep its bigint ID and URL, and add the fields the app needs in place.
create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  url text
);

alter table public.articles
  add column if not exists title text,
  add column if not exists ai_summary text,
  add column if not exists source_name text,
  add column if not exists image_url text,
  add column if not exists category text,
  add column if not exists published_at timestamptz,
  add column if not exists status public.article_status not null default 'draft',
  add column if not exists metadata jsonb not null default '{}'::jsonb,
  add column if not exists updated_at timestamptz not null default now();

alter table public.articles
  alter column published_at type timestamptz
  using case
    when published_at is null or btrim(published_at::text) = '' then null
    else published_at::text::timestamptz
  end;

update public.articles
set
  title = coalesce(title, 'Imported good-news article'),
  ai_summary = coalesce(ai_summary, 'Summary pending'),
  source_name = coalesce(source_name, 'Imported source'),
  category = coalesce(category, 'Good news'),
  published_at = coalesce(published_at, now());

alter table public.articles
  alter column title set not null,
  alter column ai_summary set not null,
  alter column source_name set not null,
  alter column category set not null,
  alter column published_at set not null;

create unique index if not exists articles_url_unique_idx
  on public.articles (url) where url is not null;

create table public.swipes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  article_id bigint not null references public.articles (id) on delete cascade,
  direction public.swipe_direction not null,
  created_at timestamptz not null default now(),
  constraint swipes_user_article_unique unique (user_id, article_id)
);

create table public.user_agendas (
  user_id uuid primary key references auth.users (id) on delete cascade,
  preferred_categories text[] not null default '{}',
  blocked_categories text[] not null default '{}',
  preference_scores jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create index articles_feed_idx
  on public.articles (published_at desc)
  where status = 'published';
create index articles_category_idx on public.articles (category);
create index swipes_user_created_idx on public.swipes (user_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger articles_set_updated_at
before update on public.articles
for each row execute function public.set_updated_at();

create trigger user_agendas_set_updated_at
before update on public.user_agendas
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data ->> 'display_name', ''), split_part(new.email, '@', 1))
  );

  insert into public.user_agendas (user_id)
  values (new.id);

  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- Also initialize accounts that existed before this migration was applied.
insert into public.profiles (id, display_name)
select
  id,
  coalesce(nullif(raw_user_meta_data ->> 'display_name', ''), split_part(email, '@', 1))
from auth.users
on conflict (id) do nothing;

insert into public.user_agendas (user_id)
select id from auth.users
on conflict (user_id) do nothing;

alter table public.profiles enable row level security;
alter table public.articles enable row level security;
alter table public.swipes enable row level security;
alter table public.user_agendas enable row level security;

create policy "Published articles are publicly readable"
on public.articles for select
to anon, authenticated
using (status = 'published');

create policy "Users can read their own profile"
on public.profiles for select
to authenticated
using ((select auth.uid()) = id);

create policy "Users can update their own profile"
on public.profiles for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create policy "Users can read their own swipes"
on public.swipes for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can create their own swipes"
on public.swipes for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can change their own swipes"
on public.swipes for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete their own swipes"
on public.swipes for delete
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can read their own agenda"
on public.user_agendas for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can update their own agenda"
on public.user_agendas for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

grant usage on schema public to anon, authenticated;
grant select on public.articles to anon, authenticated;
grant select, update on public.profiles to authenticated;
grant select, insert, update, delete on public.swipes to authenticated;
grant select, update on public.user_agendas to authenticated;
grant usage, select on sequence public.swipes_id_seq to authenticated;

-- Article writes are intentionally not granted to browser roles. n8n should
-- insert articles using its server-side Supabase credential.
