-- The Good Press initial database schema.
-- Existing n8n starter tables are preserved and upgraded in place.
create extension if not exists pgcrypto with schema extensions;
create type public.article_status as enum ('draft', 'published', 'archived');
create type public.swipe_direction as enum ('left', 'right');


create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text check (char_length(display_name) between 1 and 80),
  avatar_url text,
  theme text not null default 'system' check (theme in ('light', 'dark', 'system')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  url text
);
alter table public.articles
  add column if not exists title text,
  add column if not exists ai_summary text,
  add column if not exists source_name text,
  add column if not exists image_url text,
  add column if not exists category text,
  add column if not exists published_at timestamptz,
  add column if not exists status public.article_status not null default 'draft',
  add column if not exists metadata jsonb not null default '{}'::jsonb,
  add column if not exists updated_at timestamptz not null default now();
update public.articles set
  title = coalesce(title, 'Imported good-news article'),
  ai_summary = coalesce(ai_summary, 'Summary pending'),
  source_name = coalesce(source_name, 'Imported source'),
  category = coalesce(category, 'Good news'),
  published_at = coalesce(published_at, now());
